name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build and tag the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chegg-bot:latest .

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/chegg-bot:latest
